server:
  port: 8080

spring:
  application:
    name: OAUTH-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/OAuth?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


